// <auto-generated />
namespace OpsCenter.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208151647289_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy9XzUm+bPN6LG0/So/LIiM8Xufl+XsitfMQSH1ku6MOTwmx9vrN9SrnTj/76HR5WdTVckF9+g2p6e+VXwcf0Ecv62qV1+31q/xcXz97+lF6N3zvbvdF+5r3DjCg35btvb2P0hfrsswmJX1wnpVN/lG6+vTR67aq88/zZV5nbT57mbVEEpqZs1nOI1BKPFp9ejtiPLy7swdi3M2Wy6rNWprmHuIdNPGvQfR1WxPHfJQ+K97ls+f58qKdW2S/yN6ZT+jXj9KvlgUxGL3U1uvcH5z8vbnTp3kzrYuV4PdD7vukzkFr0+9T+uNNARp8LTBPrgdn+TZQvlrNvglkFMx7IfP4rpOSjbJDcn1eXKxrYacfSY+Ppq9XfuiMzPNChPyh9/yTWYlGP+RefyS4CmOj4BJXtFlBIqE9WEv79ElHdqX967zt8zLZY9eHGOVxwOqdUXVBBSojBizUKdHh2YE4P+KuOBLG4bg74HE8/iJbrYgnPQ9EP0lfi/txsv36/Z2MhcC4O20ivobF1vZEuim7yDvfgjSz/FlRNy2xTDbJICUns0Wv2S2mzfQUmb2uTnb0Ny/h9w6DqCsWTHQHkKPkMxocWvA4dZSE0wZPS99/Pc3KrI5o+5OqXC+WQxZj09viwvjvyye3hxD4Iz6g4Ivbw7OqyodlP3xvOFAPEUj4+PawrMbyIdkP3xtOFyfv4z6sx3c7bNNlUE+lacuOv9Dl+lvJREcNfZBUbPCCGNhNcnHD+z87khHobB/MBmW+CZ7ncgT86D6+PSx1Inw4+tHtYfxIzjqQfjblrGeYu01s78YOm7+tYVajGFhrHn83P9CzktLko5SIdFnMYCFfXzdtvhijwfj1LypPyoKZ2TT4IlsW53nTvqne5sh1kBH/+kkGGxk0zaz8f3GmoQAFboyKeqHUZh8V/5oOlpdZPZ1n9dYie3fnfZ3dSNT/QfA6AQHkAvmorwnG+eBMxfeD0QkHvi4qvXDgRlT+vxLF/6xwZiT6/jCG6kbUHwQtiJI/CNKPGP0mRu9Gvf0oK0THmrkYJ7mOYqGvWCIa+qQi5AXdMHTuDL3bVyf27fXW+T7Wn9eE4+sYoW4RP/fN8eO7flL/MWns4sKBQIp/mU+BlwNq2pwtzyszyzRYHyPTpMMEX+RtRmyQHddtcZ5NW/p6mjcNZ5NYeIiwi0k+O1t+uW5X6/a4afLFpAw8n8d3N/fPSYIQ58dfsgny/I+vPwRCswAnf7l8si7KmcX7WV99DYEAq6pOJKwom0bgLq4tpBfV8paAlHxP81W+hEZ9ky9WJQFrvly+zi7zYdxupmFIscdPi+yizhY+BeUTxeR1Rj17XVAH/huuP/qT2JVWlI7+nwAAAP//+diZ78YaAAA="; }
        }
    }
}
